@startuml

[*] --> S1_1 : Thread 1
S1_1 --> S1_2 : sleep[x]
S1_2 --> S1_3 : acquire[monitor1]
S1_3 --> S1_4 : release[monitor1]
S1_4 --> S1_5 : acquire[monitor2]
S1_5 --> [*]

[*] --> S2_1 : Thread 2
S2_1 --> S2_2 : sleep[y]
S2_2 --> S2_3 : acquire[monitor1]
S2_3 --> S2_4 : release[monitor1]
S2_4 --> S2_5 : acquire[monitor2]
S2_5 --> [*]

[*] --> S3_1 : Thread 3
S3_1 --> S3_2 : sleep[z]
S3_2 --> S3_3 : acquire[monitor1]
S3_3 --> S3_4 : release[monitor1]
S3_4 --> S3_5 : acquire[monitor2]
S3_5 --> [*]

@enduml
